export const FETCH_POST_LIST_REQUEST = 'PostList/FETCH_POST_LIST_REQUEST';
export const FETCH_POST_LIST_SUCCESS = 'PostList/FETCH_POST_LIST_SUCCESS';
export const FETCH_POST_LIST_FAILURE = 'PostList/FETCH_POST_LIST_FAILURE';