export const FETCH_POST_DETAIL_REQUEST = 'PostDetail/FETCH_POST_DETAIL_REQUEST';
export const FETCH_POST_DETAIL_SUCCESS = 'PostDetail/FETCH_POST_DETAIL_SUCCESS';
export const FETCH_POST_DETAIL_FAILURE = 'PostDetail/FETCH_POST_DETAIL_FAILURE';